name: Daily LS Trading Analysis

on:
  schedule:
    - cron: '0 13 * * 1-5'  # 13:00 UTC = 8 AM Chicago time, Monday–Friday
  workflow_dispatch:        # lets you run the workflow manually

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run LS trading analysis
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: |
          python lsproject.py > analysis_output.txt

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: trading-report
          path: |
            analysis_output.txt
            trading_report.xlsx
            trading_report.pdf
