name: Daily LS trading analysis

on:
  schedule:
    - cron: '0 13 * * 1-5'  # 13:00 UTC = 8 AM Chicago time, Monday–Friday
  workflow_dispatch:        # lets you run the workflow manually

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run LS trading analysis
        run: |
          python Ls_trading_project.py > analysis_output.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: trading-report
          path: analysis_output.txt

